# SPDX-FileCopyrightText: 2025-2026 Qoro Quantum Ltd <divi@qoroquantum.de>
#
# SPDX-License-Identifier: Apache-2.0

"""Guards how pydantic models reach the API reference.

``sphinx_automodapi`` builds a page per class by introspecting class
attributes, which for a pydantic model finds only ``model_config`` -- the
fields live in ``model_fields``. A model left to automodapi therefore renders
with no fields at all, and the docs build still succeeds, so the omission is
visible only by reading the published page.

Each public model is instead excluded with ``:skip:`` and documented by an
``autopydantic_model`` directive, which renders fields with their types,
defaults and constraints.
"""

import importlib
import re
from pathlib import Path

from pydantic import BaseModel

_API_REFERENCE = (
    Path(__file__).resolve().parents[1] / "docs" / "source" / "api_reference"
)


def _rst_sources() -> list[str]:
    return [path.read_text() for path in _API_REFERENCE.rglob("*.rst")]


def _documented_modules() -> set[str]:
    """Modules the API reference generates pages for."""
    directive = re.compile(r"^\.\.\s+automodapi::\s+(\S+)", re.MULTILINE)
    return {name for text in _rst_sources() for name in directive.findall(text)}


def _skipped_names() -> set[str]:
    """Names excluded from automodapi's generated pages."""
    directive = re.compile(r"^\s+:skip:\s+(\S+)", re.MULTILINE)
    return {name for text in _rst_sources() for name in directive.findall(text)}


def _explicitly_documented() -> set[str]:
    """Models carrying their own ``autopydantic_model`` directive."""
    directive = re.compile(r"^\.\.\s+autopydantic_model::\s+(\S+)", re.MULTILINE)
    return {name for text in _rst_sources() for name in directive.findall(text)}


def _public_models() -> dict[str, str]:
    """Public pydantic models in documented modules, keyed by dotted path."""
    found = {}
    for module_name in _documented_modules():
        module = importlib.import_module(module_name)
        for name in getattr(module, "__all__", ()):
            obj = getattr(module, name, None)
            if isinstance(obj, type) and issubclass(obj, BaseModel):
                found[f"{module_name}.{name}"] = name
    return found


def test_every_public_pydantic_model_is_documented_explicitly():
    """A model left to automodapi renders with no fields and no build error."""
    explicit = _explicitly_documented()
    missing = sorted(path for path in _public_models() if path not in explicit)
    assert not missing, (
        f"These pydantic models have no ``autopydantic_model`` directive, so their "
        f"fields will not render: {missing}. Add one in docs/source/api_reference/, "
        f"alongside a ``:skip:`` on the module's automodapi block."
    )


def test_explicitly_documented_models_are_skipped_from_automodapi():
    """Without ``:skip:`` the class is documented twice, once with no fields."""
    skipped = _skipped_names()
    unskipped = sorted(
        path for path, name in _public_models().items() if name not in skipped
    )
    assert not unskipped, (
        f"These models have an ``autopydantic_model`` directive but are still "
        f"generated by automodapi: {unskipped}. Add a ``:skip:`` for each."
    )


def test_documented_names_all_resolve_to_pydantic_models():
    """Guards the directives against a rename or a removed model."""
    stale = []
    for dotted in _explicitly_documented():
        module_name, _, attribute = dotted.rpartition(".")
        try:
            obj = getattr(importlib.import_module(module_name), attribute)
        except (ImportError, AttributeError):
            stale.append(dotted)
            continue
        if not (isinstance(obj, type) and issubclass(obj, BaseModel)):
            stale.append(dotted)

    assert not stale, f"Directives name things that are not pydantic models: {stale}"
