name: Build & Deploy Docs (Poetry) to Pages

on:
  push:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: Install doc dependencies (Poetry)
        run: poetry install --with docs

      - name: Build Sphinx HTML
        run: |
          poetry run sphinx-build -W -b html docs/source docs/_build/html
        env:
          LC_ALL: C.UTF-8
          LANG: C.UTF-8

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: docs/_build/html
          retention-days: 1

  deploy-docs:
    if: github.ref == 'refs/heads/main'
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: .

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact (built docs)
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
